### PR TITLE
[fixbug] apply negative offset on reference line of road

### PR DESCRIPTION
**Pull request by TroyeFun**
Bug description:
There is a potential bug that the sign of reference line offset is incorrect in Road.add_offset_to_reference_line in imap.lib.opendrive.road.py. Fig.1 is map Town10HD_Opt.xodr viewed in https://odrviewer.io/, Fig.2 is the result of command `imap -m imap/data/Town10HD_Opt.xodr`, and Fig.3 is the lane boundaries of the map.
Fig.1
Fig.2
Fig.3

It is obvious that the lanes in the middle of the map have some offsets compared with the true map in Fig.1.
I don't fully understand what the lane offset means. But when I set the offset to negative, the bug seems fixed. Here are the new results.
carla_HDmap_Town10HD_Opt_xodr
Town10HD_roads_negaoffset

### CODE REVIEW

**Comment by daohu527** [comment]
according to specification [9.3. Lane offset](https://www.asam.net/index.php?eID=dumpFile&t=f&f=4422&token=e590561f3c39aa2260e5442e29e93f6693d1cccd#top-05e95dfd-ce05-40c8-af93-d065229e6968).

We need to add an offset to the lane, I don't understand why we add a negative, it is positive from the coordinates

**Comment by TroyeFun** [comment]
According to the shift_t function in Point3d, the offset is added to the opposite direction of y_axis. I think this may be the cause of the problem?
https://github.com/daohu527/imap/blob/5266756fb0a92d659c484a671efec9aa2e90bcf7/imap/lib/common.py#L87
```
  def shift_t(self, offset):
    vec_x = Vector3d(math.cos(self.yaw), math.sin(self.yaw), 0)
    vec_z = Vector3d(0, math.sin(self.roll), math.cos(self.roll))
    normal_xz = vec_x.cross_product(vec_z)
    vec_y = normal_xz.normalize() * offset

    self.x += vec_y.x
    self.y += vec_y.y
    self.z += vec_y.z
```

**Comment by daohu527** [comment]
Yes, you are right. The direction of the vector is indeed reversed

**Comment by daohu527** [comment]
fixed in https://github.com/daohu527/imap/commit/ba2468a1c24ae3c19e1834895814beec8b882098

**Pull request closed without merging**
